name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: gen-lang-client-0893994648
  PROJECT_NUMBER: 388282578917
  SERVICE: bot-chat-autonomo
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          # You need to create a Workload Identity Provider and Pool in Google Cloud
          # and replace the value below with the full provider name.
          workload_identity_provider: 'projects/388282578917/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@gen-lang-client-0893994648.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker push
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$SERVICE:${{ github.sha }} .
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$SERVICE:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/${{ env.SERVICE }}:${{ github.sha }}
